version: '3.8'

services:
  postgres:
    container_name: project-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
